# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nalog', models.CharField(max_length=500)),
                ('sifra', models.CharField(max_length=500)),
                ('slika', models.FileField(upload_to='')),
                ('is_star', models.BooleanField(default=False)),
                ('kreirao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
