# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pwm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('sirina', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
            ],
        ),
    ]
