# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogon', '0003_auto_20170531_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwm',
            name='korisnik',
        ),
    ]
